language: node_js
sudo: false
node_js:
- 'node'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"

env:
  - CANARY=false
  - CANARY=true

matrix:
  fast_finish: true
  allow_failures:
    - env: CANARY=true

branches:
  only:
    - master # otherwise pull requests get built twice

install:
  - yarn install --frozen-lockfile

script:
  - ./node_modules/.bin/karma start --single-run --browsers ChromeHeadlessTravis --reporters mocha
